version: '3.8'

services:
  app:
    image: node:20.11.1-alpine3.19
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/app/.next
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data: 